Fixes EditTextPreferenceDialogFragmentCompatTest on older devices
BooleanSupplier isn't always available, which causes a java.lang.NoClassDefFoundError: java/util/function/BooleanSupplier

Fixes: b/190194402
Test: EditTextPreferenceDialogFragmentCompatTest
Change-Id: I30fa3607c0241de7b4391e72fcfdba20bf678ba9