Adding some horizontal separators to build_log_simplifier's output
to make it easier to recognize that the messages are related

Also a couple of rewordings.

Bug: 171003121

Test: Run `./busytown/impl/build.sh :help -Pandroidx.validateNoUnrecognizedMessages >/dev/null`, see this output:

  $ ./busytown/impl/build.sh :help -Pandroidx.validateNoUnrecognizedMessages >/dev/null

  ================================================================================
  build_log_simplifier.py: Error: Found 15 lines of new warning output:

  Starting a Gradle Daemon (subsequent builds will be faster)
  > Task :help

  Welcome to Gradle 6.7.

  To run a build, run gradlew <task> ...

  To see a list of available tasks, run gradlew tasks

  To see a list of command-line options, run gradlew --help

  To see more detail about a task, run gradlew help --task <task>

  For troubleshooting, visit https://help.gradle.org

  ================================================================================
  Error: build_log_simplifier.py found 15 new lines of output

    Log     : /mnt/fastroid/workspace/2-aosp-androidx-git/out/dist/gradle.log
    Baseline: /mnt/fastroid/workspace/2-aosp-androidx-git/frameworks/support/development/build_log_simplifier/messages.ignore

  Please fix or suppress these new messages in the tool that generates them.
  If you cannot, then you can exempt them by doing:

    1. cp /mnt/fastroid/workspace/2-aosp-androidx-git/out/dist/gradle.log.ignore /mnt/fastroid/workspace/2-aosp-androidx-git/frameworks/support/development/build_log_simplifier/messages.ignore # or, if this script is running on the build server, you may download this file from there
    2. modify the new lines to be more generalized (they are regular expressions) if it is more important to preemptively exempt similar messages than to be notified of new, similar messages

  Note that if you exempt these messages by updating the exemption file, this will suppress these messages in the output of CI builds but not in Android Studio.
  Additionally, adding more exemptions to this exemption file will cause the build to run more slowly than fixing or suppressing the message where it is generated.
  ================================================================================

  Build log validation, enabled by the argument -Pandroidx.validateNoUnrecognizedMessages, failed

  Failed: OUT_DIR=out DIST_DIR=/usr/local/google/workspace/2-aosp-androidx-git/frameworks/support/busytown/impl/../../../../out/dist ANDROID_HOME=./prebuilts/fullsdk-linux frameworks/support/gradlew -p frameworks/support --stacktrace -Pandroidx.summarizeStderr --no-watch-fs :help -Pandroidx.validateNoUnrecognizedMessages

Change-Id: I39b3f597da46b98084850d39d51d3c1345f812b4