MediaRouter: Handle NoSuchMethodError at MediaRouterJellybeanMr1
android.media.MediaRouter.RouteInfo.getPresentationDisplay() was
added in API 17. However, some factory release of JB MR1 missed
this API. It can cause NoSuchMethodError when
android.support.v7.media.MediaRouter.getInstance() is called.

Bug: 26273371
Change-Id: If2e814afdd537697892a5867bb684e9d130ee8e2